auctions/urls.py
from django.urls import path

from . import views


app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("wishlist", views.wishlist, name = "wishlist"),
    path("mylistings", views.mylistings, name = "mylistings"),
    path("add_listing", views.add_listing, name = "add_listing"),
    
    path("<int:listing_id>", views.listing, name = "listing"),
    path("<str:category>", views.category , name = "category"),
    path("<int:listing_id>/bid", views.bid, name = "bid"),
    path("<int:listing_id>/comment", views.comment, name = "comment"),
    path("<int:listing_id>/stopListing", views.stopListing, name = "stopListing")
    
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass



    
class Listing(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.URLField(blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    SHOPPING_CATEGORIES = [
        ("CLO", "Clothing"),
        ("HOM","Home"),
        ("TOY", "Toys"),
        ("MIS", "Miscellaneous")
    ]


    category = models.CharField(choices=SHOPPING_CATEGORIES, max_length=3, default="MIS")
    current_bid = models.DecimalField(max_digits=11, decimal_places=2, default=0.0)
    open = models.BooleanField(default=True)
    Wishers = models.ManyToManyField(User, related_name="wishes")

    


class Bid(models.Model):
    value = models.DecimalField(decimal_places=2, max_digits = 100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete = models.CASCADE, related_name = "bids" )

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete = models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

 

auctions/forms.py
from django import forms
from .models import Listing, Comment
from django.forms import ModelForm

class BidForm(forms.Form):
    bid_amount = forms.DecimalField(min_value=0, max_digits=10, decimal_places=2)

    def clean_bid_amount(self):
        bid_amount = self.cleaned_data['bid_amount']
        return bid_amount



class ListingForm(ModelForm):
    class Meta:
        model = Listing
        fields= ["title", "description", "image", "category"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]
        

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Max
from .models import User, Listing, Bid, Comment
from .forms import BidForm, ListingForm, CommentForm

def index(request):
    return render(request, "auctions/index.html",{
        "listings": Listing.objects.all(),
    })
def category(request, category):
    
    
    listings = Listing.objects.filter(category = category)
    
    for category_code, category_name in Listing.SHOPPING_CATEGORIES:
        if category_code == category:
            category = category_name


    return render(request, "auctions/category.html",{
        "category": category, 
        "listings": listings,

    })



def listing(request, listing_id):

    try:
        listing = Listing.objects.get(id=listing_id)
        print(listing.title)
        form = BidForm()
        commentForm = CommentForm()
    except Listing.DoesNotExist:
        raise Http404("Listing not found.")
    print('penis')
    bid = Bid.objects.filter(listing=listing).aggregate(Max('value'))['value__max']
    comments = Comment.objects.filter(listing = listing)
    if (bid == None):
        bid = 0
    if (request.user == listing.user):
        isUser = True
    else:
        isUser = False
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "bid": bid,
        "form": form,
        "isUser": isUser,
        "commentForm": commentForm,
        "comments": comments
        
    })

def stopListing(reqeuest, listing_id):
    try:
        listing = Listing.objects.get(pk = listing_id)
    except Listing.DoesNotExist:
        raise Http404("Listing not found")
    listing.delete()

    return HttpResponseRedirect(reverse("auctions:index"))

@login_required
def bid(request, listing_id):
     if request.method == "POST":

        try:
            print(listing_id)
            print(request.user.id)
            user = User.objects.get(pk = request.user.id)
            #user = request.user //couldnt i just do this lmao 
            listing = Listing.objects.get(pk=listing_id)
            form = BidForm(request.POST)
        except KeyError:
            return HttpResponseBadRequest("Bad Request: no listing chosen")
        except Listing.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: listing does not exist")
        except User.DoesNotExist:
            return HttpResponseBadRequest("Bad Request: user does not exist")
        if form.is_valid():

            bid_amount = form.clean_bid_amount()
            new_bid = Bid(value = bid_amount, user = user, listing = listing )
            new_bid.save()
            if (bid_amount > listing.current_bid):
                listing.current_bid = bid_amount
                return HttpResponseRedirect("/" + str(listing_id))
            else:
                #Want to add functionality to display error message when this happens
                pass

        else:
            return render(request, "auctions/error_handling.html", {
                "code": 400,
                "message": "Form is invalid"
            })

@login_required
def wishlist(request):
    wishlist_items = request.user.wishes.all()
    return render(request, "auctions/wishlist.html",{
        "wishes": wishlist_items
    })

@login_required
def mylistings(request):

    listings = Listing.objects.filter(user = request.user)
    print(listings)
    return render(request, "auctions/mylistings.html",{
        "listings":listings
    })

@login_required
def add_listing(request):
    if request.method == "POST":
        new_listing = Listing.objects.create(title = request.POST["title"], description = request.POST["description"], 
                                             image = request.POST["image"], user = request.user)
        new_listing.save()

        return HttpResponseRedirect(reverse("auctions:index"))
    if request.method == "GET":
        new_listing_form = ListingForm()


        return render(request, "auctions/add_listing.html", {
            "new_listing_form": new_listing_form,
        })

@login_required       
def comment(request, listing_id):
    if request.method == "POST":
        new_comment = Comment.objects.create(user = request.user, listing = Listing.objects.get(pk = listing_id),
                                             comment = request.POST["comment"])
        # to get listing, could also set a related name in comment i think, this would be better if I didnt want to have to
        # pass listing_id, but its fine for now
        new_comment.save()

        return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))




def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
    

auctions/templates/auctions/add_listing.html
{% extends "auctions\layout.html" %}


{% block body %}
<form action="{% url 'auctions:add_listing' %}" method = "POST">
    {% csrf_token %}
    {{new_listing_form}}
    <input type="submit">

</form>



{%endblock%}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}


    <h1>{{category}}</h1>


    {% for listing in listings %}
        <div class = "listing_button">
            <a href="{% url 'auctions:listing' listing.id %}">
                <h2 id = "dez">{{listing.title}}</h2>
                <p>{{listing.description}}</p>
                {% if listing.image is not None%}
                    <img src="{{listing.image}}" width="500px">
                {%endif%}
            </a>
        </div>

    {% endfor %}


{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <h2>Active Listings</h2>
    {% for listing in listings %}

        <div class = "listing_button">
            <a href="{% url 'auctions:listing' listing.id %}">
                <h2 id = "dez">{{listing.title}}</h2>
                <p>{{listing.description}}</p>
                {% if listing.image is not None%}
                    <img src="{{listing.image}}" width="500px">
                {%endif%}
            </a>
        </div>
        
        <p id = "dez">experiments</p>
    {%endfor%}
    
{% endblock %} 

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <div class = "dropdown">
            <li class = "nav-item">
                <p id = "categories_button" class = "nav-link">Categories</p>
                <div class = "dropdown-content">
                    <!-- Defintely a way to loop through all the categories without having to explicity state them-->
                    <a href="{% url 'auctions:category' 'HOM'%}">Home</a>
                    <br>
                    <a href="{% url 'auctions:category' 'CLO'%}">Clothes</a>
                    <br>
                    <a href="{% url 'auctions:category' 'TOY'%}">Toys</a>
                    <br>
                    <a href="{% url 'auctions:category' 'MIS'%}">Miscellaneous</a>
                </div>
            </li>
            </div>
            {% if user.is_authenticated %}
                <li class = "nav-item">
                    <a class = "nav-link" href="{% url 'auctions:wishlist' %}">My Wishlist</a>
                </li>
                <li class = "nav-item">
                    <a class = "nav-link" href="{%url 'auctions:mylistings' %}">My Listings</a>
                </li>
                <li class = "nav-item">
                    <a class = "nav-link" href="{%url 'auctions:add_listing'%}">Add Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                



            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
<h1>asdf</h1>
{% block body %}

    <h1>asdfj;salkdfj</h1>
    <h1>{{listing.description}}</h1>
    {% if listing.open %}
        <h1>{{listing.title}}</h1>
        <h1>{{listing.id}}</h1>
        <p>{{listing.description}}</p>
        <p>{{listing.open}}</p>
        <p>{{bid}}</p>
    {% endif %}
    {% if user.is_authenticated %}
        {% if isUser%}
            <form action = "{% url 'auctions:stopListing' listing.id %}" method = "POST">
                {% csrf_token %}
                <button type = "submit">Stop Listing</button>
            </form> 
        {% endif %}

    

        <form  action="{% url 'auctions:bid' listing.id %}" method = "POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Place Bid</button>
        </form>
        <form action="{%url 'auctions:comment' listing.id %}" method = "POST">
            {% csrf_token %}
            {{commentForm}}
            <button type = "submit"> Comment</button>

        </form>

    {%endif%}
    {%for comment in comments%}
        {{comment.date}}
        <br>
        {{comment.comment}}
        {%empty%}
            <p>no comments</p>

    {%endfor%}
    
    

{% endblock %}

auctions/templates/auctions/listing_page.html
<h1>here</h1>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/mylistings.html
{% extends "auctions\layout.html"%}




{%block body%}

{% for listing in listings %}

{{listing.title}}




{%endfor%}

{%endblock%}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/wishlist.html
{% extends "auctions\layout.html"%}

{%block body%}

{% for wish in wishes %}



{{wish.title}}
{% empty %}
<p>No wishes</p>

{%endfor%}

{%endblock%}